name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/dmg/*.dmg
